objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Course_Rate__c/Course_Rate__c.object-meta.xml
<CustomObject>
    <label>Course Rate</label>
    <nameField>
        <label>Course Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Course Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Course_Rate__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Course Rates</relationshipLabel>
    <relationshipName>Course_Rates</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Course_Rate__c/fields/Instructor__c.field-meta.xml
<CustomField>
    <fullName>Instructor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Instructor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Instructor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Course_Rates</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/CourseRatesTriggerHandler.cls
public class CourseRatesTriggerHandler {
    
    
    Public static void updateCourseRateName(List<Course_Rate__c> crs){
        
        set<ID> courseRateIds = new set<ID>();
        
        for (Course_Rate__c a: crs){
            
         
            courseRateIds.add(a.Id);
            a.Name = a.Instructor__r.firstname + ' ' + a.Instructor__r.lastname + ' - ' + a.Course__r.Name;
        }
       
        map<ID,Course_Rate__c> crmap = new map<ID,Course_Rate__c>([SELECT ID,Name,Instructor__r.firstname,Instructor__r.lastname,Course__r.Name FROM Course_Rate__c WHERE ID in:courseRateIds]);
        //Loops through course rates and renames with course name + instructor name
        
        
        
        for(Course_Rate__c cr: crs){
            
            cr.Name = crmap.get(cr.ID).Course__r.Name + ' - ' +crmap.get(cr.ID).Instructor__r.firstname + ' ' + crmap.get(cr.ID).Instructor__r.lastname ;
            
        }
        
    }

}