objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Course_Rate__c/Course_Rate__c.object-meta.xml
<CustomObject>
    <label>Course Rate</label>
    <nameField>
        <label>Course Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Course Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Course_Rate__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Course Rates</relationshipLabel>
    <relationshipName>Course_Rates</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Course_Rate__c/fields/Hourly_Rate__c.field-meta.xml
<CustomField>
    <fullName>Hourly_Rate__c</fullName>
    <label>Hourly Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Course_Rate__c/fields/Instructor__c.field-meta.xml
<CustomField>
    <fullName>Instructor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Instructor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Instructor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Course_Rates</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/CourseRateTriggerHandler_Test.cls
@isTest
public with sharing class CourseRateTriggerHandler_Test {


    @testSetup
    private static void testSetupObjectDataFactory() {

    Course__c newCourse = new Course__c (Name='Test Course');
    insert newCourse;
    
    
    Course_Rate__c cr = new Course_Rate__c (Name='Test', 
                    Instructor__c='0054L000000FztcQAC',
                    Course__c=newCourse.id, Hourly_Rate__c=5.0);   

    insert cr;

    Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];
    User u = [SELECT Id FROM User WHERE profileId = :p.Id LIMIT 1];
    System.runAs(u){
        }
    }

    @isTest
    public static void updateCourseRateName_Test() {

        Test.startTest();
            Course_Rate__c cr = [Select Name,Instructor__c,Course__c,Hourly_Rate__c From Course_Rate__c];
            cr.Name = '2';
            update cr;
        Test.stopTest();
        system.debug([Select Name,Instructor__c,Course__c,Hourly_Rate__c From Course_Rate__c]);

        Course_Rate__c output = [SELECT Name FROM Course_Rate__c Limit 1 ];
        String outputString = output.Name;
        System.assertEquals('Test Course - Mary Stevens', outputString);

    }
}