objects/AutoNumber__c/AutoNumber__c.object-meta.xml
<CustomObject>
    <label>AutoNumber</label>
    <nameField>
        <label>AutoNumber Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AutoNumbers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AutoNumber__c/fields/Course_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Course_Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course Invoice</label>
    <referenceTo>Course_Invoice__c</referenceTo>
    <relationshipLabel>AutoNumbers</relationshipLabel>
    <relationshipName>AutoNumbers</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/AutoNumber__c/fields/Expense_Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Expense_Invoice_Number__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Expense Invoice Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/AutoNumber__c/fields/Service_Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Service_Invoice_Number__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Service Invoice Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Course_Invoice__c/Course_Invoice__c.object-meta.xml
<CustomObject>
    <label>Course Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Course Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Course_Invoice__c/fields/Expense_Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Expense_Invoice_Number__c</fullName>
    <formula>SUBSTITUTE(Name, Name , Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Expense Invoice Number</label>
    <type>Text</type>
</CustomField>

classes/InvoiceTriggerHandler.cls
public class InvoiceTriggerHandler {
    
    Public static void UpdateAutoNumbers(List<Course_Invoice__c>courseInvoice){

    AutoNumber__c serviceNumber = [SELECT Service_Invoice_Number__c FROM AutoNumber__c WHERE Name = 'Service Invoice Number' Limit 1]; 
    AutoNumber__c expenseNumber = [SELECT Expense_Invoice_Number__c FROM AutoNumber__c WHERE Name = 'Expense Invoice Number' Limit 1];

    
        
    List<AutoNumber__c> updateList = new List<AutoNumber__c>()  ;
    
    String serviceRecordType = Schema.SObjectType.Course_Invoice__c.getRecordTypeInfosByName().get('Service Invoice').getRecordTypeId();
    String expenseRecordType = Schema.SObjectType.Course_Invoice__c.getRecordTypeInfosByName().get('Expense Invoice').getRecordTypeId();
    
    for(Course_Invoice__c  i:courseInvoice){
        if (i.RecordTypeId == serviceRecordType){
            
            Decimal decSize = serviceNumber.Service_Invoice_Number__c.intValue(); 
            String stringSize = decSize.toPlainString();
            
            Integer size = stringSize.length();
            Integer addZeros = 4-size;
            String zeros = '';
            
            for(Integer k = 0; k < addZeros; k++){
                zeros += 0;
            }
            
            i.Name = 'INV-{' + zeros + serviceNumber.Service_Invoice_Number__c + '}';  //0124L0000000AopQAE
            
            serviceNumber.Service_Invoice_Number__c++;

            // AutoNumber__c serviceNumberUpdate = serviceNumber[0];
            // serviceNumberUpdate.Service_Invoice_Number__c ++;
            //updateList.add(serviceNumberUpdate);
                      
        }
        
        else if(i.RecordTypeId == expenseRecordType){
            
            Decimal decSizeE = expenseNumber.Expense_Invoice_Number__c.intValue(); 
            String stringSizeE = decSizeE.toPlainString();
            
            Integer sizeE = stringSizeE.length();
            Integer addZerosE = 4-sizeE;
            String zerosE = '';
            
            for(Integer k = 0; k < addZerosE; k++){
                zerosE += 0;
            }
            
            i.Name = 'EXPINV-{' + zerosE + expenseNumber.Expense_Invoice_Number__c + '}';  //0124L0000000Atf 
            expenseNumber.Expense_Invoice_Number__c++;

            // AutoNumber__c expenseNumberUpdate = expenseNumber;
            // expenseNumberUpdate.Expense_Invoice_Number__c ++;
            // updateList.add(expenseNumberUpdate);
            
        }
    }
        update serviceNumber;
        update expenseNumber;
    }
}