objects/Course_Invoice__c/Course_Invoice__c.object-meta.xml
<CustomObject>
    <label>Course Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Course Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Course_Invoice__c/fields/Course_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Course_Opportunity__c</fullName>
    <label>Course Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Course Invoices</relationshipLabel>
    <relationshipName>Course_Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

classes/InoviceCloneInvoke.cls
public with sharing class InoviceCloneInvoke {

    Public class FlowInput{
        @InvocableVariable public ID Id;
    }

    @InvocableMethod(label='Expense Invoice Clone' description='')
    public static void InoviceCloneInvoke(list<FlowInput> request) {


        ID Id = request[0].Id;

        List<Course_Invoice__c> ciList = new List<Course_Invoice__c>();

                
        InvoiceClone.InvoiceClone();

        Course_Invoice__c c = [SELECT ID,NAME, Status__c,Submitted_Date__c,Course_Opportunity__c FROM Course_Invoice__c where name = 'EXPINV-{0008}'];

        List<Course_Invoice__c> ci = new List<Course_Invoice__c>();
        ci.add(c);

        InvoiceClone.InvoiceClone(ci);

    }
}